language: php

matrix:
    include:
        - php: 7.2
          env: COMPOSER_PARAMETERS="--prefer-lowest"
        - php: 7.3
        - php: 7.4
        - php: nightly
    allow_failures:
        - php: nightly

before_script:
    - if [[ $TRAVIS_PHP_VERSION = "nightly" ]]; then composer remove friendsofphp/php-cs-fixer --no-interaction --dev --no-update; fi;
    - composer update --prefer-stable --no-interaction $COMPOSER_PARAMETERS

script:
    - if [[ $TRAVIS_PHP_VERSION != "nightly" ]]; then vendor/bin/php-cs-fixer fix --allow-risky=yes --diff --ansi --dry-run; fi;
    - vendor/bin/psalm
    - vendor/bin/phpunit --colors=always