language: php

matrix:
    include:
        - php: 7.2
          env: COMPOSER_PARAMETERS="--prefer-lowest"
        - php: 7.3
        - php: 7.4
        - php: nightly

before_script:
    - if [[ $TRAVIS_PHP_VERSION = "nightly" ]]; then composer remove friendsofphp/php-cs-fixer --no-interaction --dev --no-update; fi;
    - if [[ $TRAVIS_PHP_VERSION = "nightly" ]]; then composer remove psalm/plugin-symfony vimeo/psalm  --no-interaction --dev --no-update; fi;
    - composer update --prefer-stable --no-interaction $COMPOSER_PARAMETERS

script:
    - if [[ $TRAVIS_PHP_VERSION != "nightly" ]]; then composer cs-check; fi;
    - if [[ $TRAVIS_PHP_VERSION != "nightly" ]]; then composer psalm; fi;
    - composer test