language: php

matrix:
    include:
        - php: 7.0
          env: deps=low
        - php: 7.1
        - php: 7.2
        - php: 7.3
        - php: 7.4snapshot
    allow_failures:
        - php: 7.4snapshot

before_script:
    - composer install -n
    - if [ "deps" = "low" ]; then composer update --prefer-lowest --prefer-stable -n; fi;