parameters:
    boshurik_telegram_bot.telegram.class: BoShurik\TelegramBotBundle\Telegram\Telegram

    boshurik_telegram_bot.api.class: TelegramBot\Api\BotApi

    boshurik_telegram_bot.updates_command.class: BoShurik\TelegramBotBundle\Command\UpdatesCommand
    boshurik_telegram_bot.updates_command.name: "telegram:updates"

    boshurik_telegram_bot.webhook_command.class: BoShurik\TelegramBotBundle\Command\WebhookCommand
    boshurik_telegram_bot.webhook_command.name: "telegram:webhook"

    boshurik_telegram_bot.api.token:
    boshurik_telegram_bot.api.tracker_token:
    boshurik_telegram_bot.api.proxy:

services:
    BoShurik\TelegramBotBundle\Telegram\Telegram: '@boshurik_telegram_bot.telegram'
    TelegramBot\Api\BotApi: '@boshurik_telegram_bot.api'
    BoShurik\TelegramBotBundle\Command\UpdatesCommand: '@boshurik_telegram_bot.updates_command'
    BoShurik\TelegramBotBundle\Command\WebhookCommand: '@boshurik_telegram_bot.webhook_command'

    boshurik_telegram_bot.telegram:
        class: "%boshurik_telegram_bot.telegram.class%"
        public: true
        arguments:
            - "@boshurik_telegram_bot.api"
            - "@event_dispatcher"

    boshurik_telegram_bot.api:
        class: "%boshurik_telegram_bot.api.class%"
        public: true
        arguments:
            - "%boshurik_telegram_bot.api.token%"
            - "%boshurik_telegram_bot.api.tracker_token%"
        calls:
            - ["setProxy", ["%boshurik_telegram_bot.api.proxy%"]]

    boshurik_telegram_bot.updates_command:
        class: "%boshurik_telegram_bot.updates_command.class%"
        arguments:
            - "%boshurik_telegram_bot.updates_command.name%"
            - "@boshurik_telegram_bot.telegram"
        tags:
            - { name: console.command }

    boshurik_telegram_bot.webhook_command:
        class: "%boshurik_telegram_bot.webhook_command.class%"
        arguments:
            - "%boshurik_telegram_bot.webhook_command.name%"
            - "@boshurik_telegram_bot.api"
        tags:
            - { name: console.command }