parameters:
    boshurik_telegram_bot.telegram.class: BoShurik\TelegramBotBundle\Telegram\Telegram

    boshurik_telegram_bot.api.class: TelegramBot\Api\BotApi

    boshurik_telegram_bot.api.token:
    boshurik_telegram_bot.api.tracker_token:
    boshurik_telegram_bot.api.proxy:

services:
    BoShurik\TelegramBotBundle\Telegram\Telegram: '@boshurik_telegram_bot.telegram'
    TelegramBot\Api\BotApi: '@boshurik_telegram_bot.api'

    boshurik_telegram_bot.telegram:
        class: "%boshurik_telegram_bot.telegram.class%"
        public: true
        arguments:
            - "@boshurik_telegram_bot.api"
            - "@event_dispatcher"

    boshurik_telegram_bot.api:
        class: "%boshurik_telegram_bot.api.class%"
        public: true
        arguments:
            - "%boshurik_telegram_bot.api.token%"
            - "%boshurik_telegram_bot.api.tracker_token%"
        calls:
            - ["setProxy", ["%boshurik_telegram_bot.api.proxy%"]]

    BoShurik\TelegramBotBundle\Command\UpdatesCommand:
        arguments:
            - "@boshurik_telegram_bot.telegram"
        tags:
            - { name: console.command }

    BoShurik\TelegramBotBundle\Command\Webhook\SetCommand:
        arguments:
            - "@boshurik_telegram_bot.api"
        tags:
            - { name: console.command }

    BoShurik\TelegramBotBundle\Command\Webhook\UnsetCommand:
        arguments:
            - "@boshurik_telegram_bot.api"
        tags:
            - { name: console.command }