services:
    BoShurik\TelegramBotBundle\Authenticator\TelegramAuthenticator:
        arguments:
            - '@BoShurik\TelegramBotBundle\Authenticator\TelegramLoginValidator'
            - '@BoShurik\TelegramBotBundle\Authenticator\UserLoaderInterface'
            - '@?BoShurik\TelegramBotBundle\Authenticator\UserFactoryInterface'
            - '@Symfony\Component\Routing\Generator\UrlGeneratorInterface'
            - '%boshurik_telegram_bot.guard.guard_route%'
            - '%boshurik_telegram_bot.guard.default_target_route%'
            - '%boshurik_telegram_bot.guard.login_route%'

    BoShurik\TelegramBotBundle\Authenticator\TelegramLoginValidator:
        arguments:
            - '%boshurik_telegram_bot.api.token%'

