parameters:
    boshurik_telegram_bot.command_listener.class: BoShurik\TelegramBotBundle\EventListener\CommandListener

services:
    BoShurik\TelegramBotBundle\EventListener\CommandListener: '@boshurik_telegram_bot.command_listener'

    BoShurik\TelegramBotBundle\Telegram\Command\CommandRegistry:
        arguments:
            - []

    boshurik_telegram_bot.command_listener:
        class: "%boshurik_telegram_bot.command_listener.class%"
        arguments:
            - "@boshurik_telegram_bot.api"
            - "@BoShurik\TelegramBotBundle\Telegram\Command\CommandRegistry"
        tags:
            - { name: kernel.event_listener, event: boshurik_telegram_bot.update, method: onUpdate }