on:
    - pull_request
    - push

name: Tests

jobs:
    tests:
        name: PHP ${{ matrix.php }}-${{ matrix.os }}-deps-${{ matrix.deps }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                php:
                    - "8.0"
                    - "8.1"
                    - "8.2"
                    - "8.3"
                    - "8.4"
                deps:
                    - latest
                    - lowest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v2.3.4

            -
                name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    tools: composer:v2

            -
                name: Determine composer cache directory
                run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

            -
                name: Cache dependencies installed with composer
                uses: actions/cache@v4
                with:
                    path: ${{ env.COMPOSER_CACHE_DIR }}
                    key: php${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
                    restore-keys: |
                        php${{ matrix.php }}-composer-{{ matrix.deps }}-
            -
                name: Update composer
                run: composer self-update

            -
                name: Install dependencies with composer
                if: matrix.deps == 'latest'
                run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

            -
                name: Install lowest dependencies with composer
                if: matrix.deps == 'lowest'
                run: composer update --prefer-lowest --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

            -
                name: Run tests with phpunit
                run: vendor/bin/simple-phpunit --colors=always